In [3]:
import pandas as pd
from pandas import Series,DataFrame

In [2]:
obj=pd.Series([4,-2,8,6])
obj

0    4
1   -2
2    8
3    6
dtype: int64

In [3]:
obj.values

array([ 4, -2,  8,  6], dtype=int64)

In [4]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [5]:
obj=pd.Series([4,-3,5,-7],index=['d','b','a','c'])
obj

d    4
b   -3
a    5
c   -7
dtype: int64

In [6]:
obj[obj>0]

d    4
a    5
dtype: int64

In [7]:
obj*2

d     8
b    -6
a    10
c   -14
dtype: int64

还可以将Series看成是有定长的有序字典，因为它是索引值到数据值的一个映射

In [8]:
sdata={'aw':4566,'sd':7412,'qw':789,'zx':5223}
obj3=pd.Series(sdata)
obj3

aw    4566
sd    7412
qw     789
zx    5223
dtype: int64

In [9]:
states=['aw','qw','zx','fg']
obj4=pd.Series(sdata,index=states)
obj4

aw    4566.0
qw     789.0
zx    5223.0
fg       NaN
dtype: float64

pandasz中的isnull和notnull可用于检测缺失数据

In [10]:
pd.isnull(obj4)

aw    False
qw    False
zx    False
fg     True
dtype: bool

In [ ]:
Serise对象本身及其索引都有一个name属性

In [36]:
obj4.name='population'
obj4.index.name='state'
obj4

state
aw    4566.0
qw     789.0
zx    5223.0
fg       NaN
Name: population, dtype: float64

In [37]:
data={'state':['ohio','ohio','nevada','nevada'],
     'year':[2000,2001,2002,2002],
     'pop':[1.5,1.7,3.6,2.4]}
frame=pd.DataFrame(data)

In [38]:
frame

state  year  pop
0    ohio  2000  1.5
1    ohio  2001  1.7
2  nevada  2002  3.6
3  nevada  2002  2.4

In [39]:
如果制定了列序列，则DataFrame的列就会按照指定顺序进行排序

SyntaxError: invalid character in identifier (<ipython-input-39-a91dedabf9da>, line 1)

In [40]:
pd.DataFrame(data,columns=['year','state','pop'])

year   state  pop
0  2000    ohio  1.5
1  2001    ohio  1.7
2  2002  nevada  3.6
3  2002  nevada  2.4

In [41]:
frame2=pd.DataFrame(data,columns=['year','state','pop','debt'],
                   index=['one','two','three','four'])
frame2

year   state  pop debt
one    2000    ohio  1.5  NaN
two    2001    ohio  1.7  NaN
three  2002  nevada  3.6  NaN
four   2002  nevada  2.4  NaN

In [42]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [43]:
frame2['state']

one        ohio
two        ohio
three    nevada
four     nevada
Name: state, dtype: object

In [44]:
frame2['year']

one      2000
two      2001
three    2002
four     2002
Name: year, dtype: int64

In [45]:
frame2.loc['three']

year       2002
state    nevada
pop         3.6
debt        NaN
Name: three, dtype: object

In [46]:
将列表或数组赋给某个列时，其长度必须跟DataFrame的长度相匹配。如果赋值是个Series,就会精确匹配DataFrame的索引

SyntaxError: invalid character in identifier (<ipython-input-46-5438ed668ae6>, line 1)

In [47]:
val=pd.Series([-1.2,-1.5,-1.7],index=['two','four','three'])
frame2['data']=val
frame2

year   state  pop debt  data
one    2000    ohio  1.5  NaN   NaN
two    2001    ohio  1.7  NaN  -1.2
three  2002  nevada  3.6  NaN  -1.7
four   2002  nevada  2.4  NaN  -1.5

In [66]:
pop={'nevada':{2001:2.4,2002:2.8},
    'ohio':{2000:1.5,2001:1.7,2002:3.6}}
pop

{'nevada': {2001: 2.4, 2002: 2.8}, 'ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [10]:
frame3=pd.DataFrame(pop, index=[2000,2001,2002])
frame3.columns

NameError: name 'pop' is not defined

In [11]:
pd.DataFrame(pop,index=[2000,2001,2001])

NameError: name 'pop' is not defined

In [13]:
frame3.index.name='year';frame3.columns.name='state'
frame3

NameError: name 'frame3' is not defined

In [14]:
pdata={'ohio':frame3['ohio'][:],
      'nevada':frame3['nevada'][:2]}
pd.DataFrame(pdata)

NameError: name 'frame3' is not defined

In [ ]:
frame3.values

In [ ]:
索引对象

In [15]:
obj=pd.Series([4.5,7.2,-5.3,3.6],index=['d','b','a','c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [16]:
obj2=obj.reindex(['a','b','c','d','e'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [17]:
obj3=pd.Series(['blue','purple','yellow'],index=[0,2,4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [18]:
obj3.reindex(range(6),method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

相关系数与协方差

In [20]:
import pandas_datareader.data as web

In [21]:
all_data={ticker:web.get_data_yahoo(ticker)
         for ticker in ['AAPL','IBM','MSFT','GOOG']}
price=pd.DataFrame({ticker:data['Adj Close']
                   for ticker,data in all_data.items()})
volumn=pd.DataFrame({ticker:data['Volume']
                    for ticker,data in all_data.items()})

In [22]:
returns=price.pct_change()
returns.tail()

AAPL       IBM      MSFT      GOOG
Date                                              
2019-02-25  0.007284  0.001508  0.005587 -0.000874
2019-02-26  0.000574  0.001864  0.006900  0.005165
2019-02-27  0.003098 -0.003936 -0.001691  0.000825
2019-02-28 -0.009836 -0.007473 -0.001248  0.003468
2019-03-01  0.010511  0.007746  0.004463  0.018814

In [23]:
returns['MSFT'].corr(returns['IBM'])

0.4866831097879074

In [24]:
returns['MSFT'].cov(returns['IBM'])

8.734718905795014e-05

In [25]:
returns.MSFT.corr(returns.IBM)

0.4866831097879074

In [26]:
returns.corr()

AAPL       IBM      MSFT      GOOG
AAPL  1.000000  0.372080  0.450247  0.457481
IBM   0.372080  1.000000  0.486683  0.408324
MSFT  0.450247  0.486683  1.000000  0.537512
GOOG  0.457481  0.408324  0.537512  1.000000

In [27]:
returns.cov()

AAPL       IBM      MSFT      GOOG
AAPL  0.000271  0.000076  0.000108  0.000116
IBM   0.000076  0.000153  0.000087  0.000078
MSFT  0.000108  0.000087  0.000211  0.000121
GOOG  0.000116  0.000078  0.000121  0.000238

pandas的索引对象负责管理轴标签，或者轴名称。构建Series时或DataFrame，所用到的任何数组或其他序列的标签都会被转换成一个index

In [29]:
obj=pd.Series(range(3),index=['a','b','c'])
index=obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [30]:
index[1:]

Index(['b', 'c'], dtype='object')

In [31]:
index[1]='d'

TypeError: Index does not support mutable operations

In [32]:
import numpy as np
labels=pd.Index(np.arange(3))
labels

Int64Index([0, 1, 2], dtype='int64')

In [33]:
obj2=pd.Series([1.5,-2.5,0],index=labels)
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

pands对象一个重要方法就是reindex,其作用时创建一个新对象

In [35]:
obj=pd.Series([4.5,2.6,-5.3,3.6],index=['d','b','a','c'])
obj

d    4.5
b    2.6
a   -5.3
c    3.6
dtype: float64

In [36]:
obj2=obj.reindex(['a','b','c','d','e'])
obj2

a   -5.3
b    2.6
c    3.6
d    4.5
e    NaN
dtype: float64

In [37]:
obj3.reindex(range(6),method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

丢弃某个轴上的项，drop返回的是一个在指定轴删除了指定值的新对象

In [38]:
obj=pd.Series(np.arange(5.),index=['a','b','c','e','d'])
obj

a    0.0
b    1.0
c    2.0
e    3.0
d    4.0
dtype: float64

In [39]:
obj.drop(['d','a'])

b    1.0
c    2.0
e    3.0
dtype: float64

索引，选取和过滤

In [41]:
data=pd.DataFrame(np.arange(16).reshape((4,4)),
                  index=['oxio','chsads','udsj','nasiue'],
                 columns=['ones','two','three','four'])
data

ones  two  three  four
oxio       0    1      2     3
chsads     4    5      6     7
udsj       8    9     10    11
nasiue    12   13     14    15

In [42]:
data['two']

oxio       1
chsads     5
udsj       9
nasiue    13
Name: two, dtype: int32

In [43]:
data[:2]

ones  two  three  four
oxio       0    1      2     3
chsads     4    5      6     7

In [44]:
data[data['three']>5]

ones  two  three  four
chsads     4    5      6     7
udsj       8    9     10    11
nasiue    12   13     14    15

In [ ]:
使用轴标签loc,整数索引iloc,从DataFrame中选择行和列的子集

In [45]:
data.loc['chsads',['two','three']]

two      5
three    6
Name: chsads, dtype: int32

In [46]:
data.iloc[2,[3,0,1]]

four    11
ones     8
two      9
Name: udsj, dtype: int32

In [47]:
data.iloc[2]

ones      8
two       9
three    10
four     11
Name: udsj, dtype: int32

In [ ]:
用这个索引也适用于标签的切片

In [48]:
data.loc[:'udsj','two']

oxio      1
chsads    5
udsj      9
Name: two, dtype: int32

In [49]:
data.iloc[:,:3][data.three>5]

ones  two  three
chsads     4    5      6
udsj       8    9     10
nasiue    12   13     14

In [ ]:
在算术方法中填充值：在不同索引的对象进行算术运算时，你可能希望当一个对象中某个轴标签在另一个对象中找不到时填充一个特殊值

In [51]:
df1=pd.DataFrame(np.arange(12.).reshape((3,4)),columns=list('abcd'))
df2=pd.DataFrame(np.arange(20.).reshape((4,5)),columns=list('abcde'))
df2.loc[1,'b']=np.nan
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [52]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [53]:
df1+df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

使用df1的add方法，传入df2以及一个fill_value参数

In [54]:
df1.add(df2,fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

他们每一个都有一个副本，以字母r开头，会反转参数

In [56]:
1/df1

a         b         c         d
0       inf  1.000000  0.500000  0.333333
1  0.250000  0.200000  0.166667  0.142857
2  0.125000  0.111111  0.100000  0.090909

In [57]:
df1.rdiv(1)

a         b         c         d
0       inf  1.000000  0.500000  0.333333
1  0.250000  0.200000  0.166667  0.142857
2  0.125000  0.111111  0.100000  0.090909

DataFrame Series之间的运算
计算一个二维数组与其某行之间的差值

In [58]:
arr=np.arange(12.).reshape((3,4))
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [59]:
arr[0]

array([0., 1., 2., 3.])

In [60]:
arr-arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

当我i们聪arr减去arr[0]的时候，每一行都执行这个操作，这就叫广播

In [63]:
frame=pd.DataFrame(np.arange(12.).reshape((4,3)),
                   columns=list('bde'),
                  index=['df','gt','hy','ui'])
series=frame.iloc[0]
frame

b     d     e
df  0.0   1.0   2.0
gt  3.0   4.0   5.0
hy  6.0   7.0   8.0
ui  9.0  10.0  11.0

In [64]:
series

b    0.0
d    1.0
e    2.0
Name: df, dtype: float64

iloc是对整数索引iloc[2]这样，里面只能放第几行，loc['colorado']这样叫轴标签索引

In [65]:
frame-series

b    d    e
df  0.0  0.0  0.0
gt  3.0  3.0  3.0
hy  6.0  6.0  6.0
ui  9.0  9.0  9.0

如果某个索引在DataFrame的列或者Series的行找不到，则参与运算的两个对象就会被重新索引以形成并集

In [68]:
series2=pd.Series(range(3),index=['b','e','f'])
frame+series2

b   d     e   f
df  0.0 NaN   3.0 NaN
gt  3.0 NaN   6.0 NaN
hy  6.0 NaN   9.0 NaN
ui  9.0 NaN  12.0 NaN

In [69]:
def f(x):
    return pd.Series([x.min(),x.max()],index=['min','max'])
frame.apply(f)

b     d     e
min  0.0   1.0   2.0
max  9.0  10.0  11.0

In [70]:
format=lambda x:'%.2f'% x
frame.applymap(format)

b      d      e
df  0.00   1.00   2.00
gt  3.00   4.00   5.00
hy  6.00   7.00   8.00
ui  9.00  10.00  11.00

之所以叫applymap，是因为Series有一个应用于元素级函数的map方法

In [71]:
frame['e'].map(format)

df     2.00
gt     5.00
hy     8.00
ui    11.00
Name: e, dtype: object

排序和排名，要对行或列索引进行排序(按照字典顺序)，可使用sort_index方法

In [72]:
obj=pd.Series(range(4),index=['d','a','b','c'])
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

若要按照值对字典进行哦挨训，可使用sort_value方法

In [73]:
obj=pd.Series([4,-7,5,3])
obj.sort_values()

1   -7
3    3
0    4
2    5
dtype: int64

在排序时，任何缺失值都会被放到Series的末尾

In [76]:
obj=pd.Series([4,np.nan,7,np.nan,-3,2])
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

当排序一个DataFrame时，你可以希望根据一个或多个列中进行排序。将一个或多个列名字传递给sort_values的by选项可实现

In [77]:
frame=pd.DataFrame({'b':[4,-7,3,2],'a':[0,1,0,1]})
frame

b  a
0  4  0
1 -7  1
2  3  0
3  2  1

In [78]:
frame.sort_values(by='b')

b  a
1 -7  1
3  2  1
2  3  0
0  4  0

In [79]:
obj=pd.Series([7,-5,7,4,2,0,4])
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

rank是为各组分配一个平均排名，的方式破坏评级关系

In [80]:
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

根据在原数组中出现的顺序排序

In [81]:
frame=pd.DataFrame({'b':[4.3,7,-3,2],'a':[0,1,0,1],
                   'c':[-2,5,6,-2.5]})
frame

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  6.0
3  2.0  1 -2.5

In [82]:
frame.rank(axis='columns')

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

汇总和计算描述统计

In [85]:
df=pd.DataFrame([[1.4,np.nan],[7.1,-4.5],[np.nan,np.nan],[0.75,-1.3]],
               index=['a','b','c','d'],
                columns=['one','two'])
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

调用DataFrame的方法将会返回到一个含有列的和的Series

In [86]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [87]:
df.sum(axis=1)

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

第6章 数据加载，储存

读写文本格式的数据，pandas提供了一些用于将表格型数据读取为DataFrame对象的函数

read_csv:从文件，URL，文件型对象加载带分隔符的数据，默认分隔符为逗号
read_table:。。。同上，默认分隔符为（\t）

In [104]:
!type examples\ex1.csv

a,b,c,d,message
1,2,3,4,hello
5,6,7,8,world
9,10,11,12,foo


In [92]:
df=pd.read_csv('examples/ex1.csv')
df

a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [97]:
pd.read_table('examples/ex1.csv',sep=',')

a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [101]:
pd.read_csv('examples/ex2.csv',header=None)

0   1   2   3      4
0  1   2   3   4  hello
1  5   6   7   8  world
2  9  10  11  12    foo

In [103]:
names=['a','b','c','d','message']
pd.read_csv('examples/ex2.csv',names=names,index_col='message')

a   b   c   d
message               
hello    1   2   3   4
world    5   6   7   8
foo      9  10  11  12

如果希望将多个列做成层次化索引，只需要传入列编号列名组成的列表

In [105]:
!type examples\csv_mindex.csv

key1,key2,value1,value2
one,a,1,2
one,b,3,4
one,c,5,6
one,d,7,8
two,a,9,10
two,b,11,12
two,c,13,14
two,d,15,16


In [106]:
parsed=pd.read_csv('examples\csv_mindex.csv',index_col=['key1','key2'])
parsed

value1  value2
key1 key2                
one  a          1       2
     b          3       4
     c          5       6
     d          7       8
two  a          9      10
     b         11      12
     c         13      14
     d         15      16

有些情况表格可能不是用固定的分隔符去分割字段，这种情况下，可以传递一个正则表达式\s+作为read_table的分隔符

In [107]:
list(open('examples/ex3.txt'))

['            A         B         C\n',
 'aaa -0.264438 -1.026059 -0.619500\n',
 'bbb  0.927272  0.302904 -0.032399\n',
 'ccc -0.264273 -0.386314 -0.217601\n',
 'ddd -0.871858 -0.348382  1.100491\n']

In [108]:
result=pd.read_table('examples/ex3.txt',sep='\s+')
result

A         B         C
aaa -0.264438 -1.026059 -0.619500
bbb  0.927272  0.302904 -0.032399
ccc -0.264273 -0.386314 -0.217601
ddd -0.871858 -0.348382  1.100491

缺失值处理是文件解析任务中一个重要组成部分，缺失数据要么没有，要么用某个标记值表示。如Null,NA

In [110]:
!type examples\ex4.csv


# hey!
a,b,c,d,message
# just wanted to make things more difficult for you
# who reads CSV files with computers, anyway?
1,2,3,4,hello
5,6,7,8,world
9,10,11,12,foo


In [111]:
pd.read_csv('examples\ex4.csv',skiprows=[0,2,3])

a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [112]:
!type examples\ex5.csv

something,a,b,c,d,message
one,1,2,3,4,NA
two,5,6,,8,world
three,9,10,11,12,foo


In [113]:
result=pd.read_csv('examples\ex5.csv')
result

something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [114]:
pd.isnull(result)

something      a      b      c      d  message
0      False  False  False  False  False     True
1      False  False  False   True  False    False
2      False  False  False  False  False    False

na_values可以用一个列表或集合的字符串表示缺失值

In [116]:
result=pd.read_csv('examples\ex5.csv',na_values=['NULL'])
result

something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

字典的各列可以使用不同的NA标记值

In [119]:
sentinels={'message':['foo','world'],'something':['two']}
pd.read_csv('examples\ex5.csv',na_values=sentinels)

something  a   b     c   d  message
0       one  1   2   3.0   4      NaN
1       NaN  5   6   NaN   8      NaN
2     three  9  10  11.0  12      NaN

逐块读取文本文件

在看大文件前，我们先设置pandas显示的更紧凑一点

In [120]:
pd.options.display.max_rows=10

In [121]:
result=pd.read_csv('examples\ex6.csv')
result

one       two     three      four key
0     0.467976 -0.038649 -0.295344 -1.824726   L
1    -0.358893  1.404453  0.704965 -0.200638   B
2    -0.501840  0.659254 -0.421691 -0.057688   G
3     0.204886  1.074134  1.388361 -0.982404   R
4     0.354628 -0.133116  0.283763 -0.837063   Q
...        ...       ...       ...       ...  ..
9995  2.311896 -0.417070 -1.409599 -0.515821   L
9996 -0.479893 -0.650419  0.745152 -0.646038   E
9997  0.523331  0.787112  0.486066  1.093156   K
9998 -0.362559  0.598894 -1.843201  0.887292   G
9999 -0.096376 -1.012999 -0.657431 -0.573315   0

[10000 rows x 5 columns]

In [123]:
pd.read_csv('examples\ex6.csv',nrows=5)

one       two     three      four key
0  0.467976 -0.038649 -0.295344 -1.824726   L
1 -0.358893  1.404453  0.704965 -0.200638   B
2 -0.501840  0.659254 -0.421691 -0.057688   G
3  0.204886  1.074134  1.388361 -0.982404   R
4  0.354628 -0.133116  0.283763 -0.837063   Q

要逐块读取文件，可以指定chunksize(行数)

In [127]:
chunker=pd.read_csv('examples\ex6.csv',chunksize=1000)
chunker

In [128]:
chunker=pd.read_csv('examples\ex6.csv',chunksize=1000)
tot=pd.Series([])
for piece in chunker:
    tot=tot.add(piece['key'].value_counts(),fill_value=0)
tot=tot.sort_values(ascending=False)

In [129]:
tot[:10]

E    368.0
X    364.0
L    346.0
O    343.0
Q    340.0
M    338.0
J    337.0
F    335.0
K    334.0
H    330.0
dtype: float64

将数据写出到文本格式

In [130]:
data=pd.read_csv('examples\ex5.csv')
data

something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [133]:
data.to_csv('examples\out.csv')
!type examples\out.csv

,something,a,b,c,d,message
0,one,1,2,3.0,4,
1,two,5,6,,8,world
2,three,9,10,11.0,12,foo


当然还可以使用其他分隔符

In [134]:
import sys
data.to_csv(sys.stdout,sep='|')

|something|a|b|c|d|message
0|one|1|2|3.0|4|
1|two|5|6||8|world
2|three|9|10|11.0|12|foo


如果没有设置其他选项，则会写出行和列的标签，当然，可以被禁用

In [135]:
data.to_csv(sys.stdout,index=False,header=False)

one,1,2,3.0,4,
two,5,6,,8,world
three,9,10,11.0,12,foo


此外，还可以只写出一部分的列，并以你制定的顺序

In [136]:
data.to_csv(sys.stdout,index=False,columns=['a','b','c'])

a,b,c
1,2,3.0
5,6,
9,10,11.0


Series也有一个to_csv的方法

In [144]:
datas=pd.date_range('1/1/2000',periods=7)
ts=pd.Series(np.arange(7),index=datas)
ts.to_csv('examples/tseries.csv')


In [142]:
!type examples\tseries.csv

2000-01-01,0
2000-01-02,1
2000-01-03,2
2000-01-04,3
2000-01-05,4
2000-01-06,5
2000-01-07,6
