元组中储存的对象可能是可变对象，一旦创建了元组，对象就不可以再修改了

In [3]:
tup=tuple(['foo',[1,2,3],True])
tup[2]=False

TypeError: 'tuple' object does not support item assignment

In [4]:
tup[1].append(4)
tup

('foo', [1, 2, 3, 4], True)

拆分元组

In [5]:
tup=(3,4,5)
a,b,c=tup
b

4

使用这个功能，可以很容易的替换变量名字

In [6]:
a,b=1,2
a

1

In [7]:
b

2

In [8]:
a,b=b,a
a

2

In [9]:
b

1

In [10]:
seq=[(1,2,3),(4,5,6),(7,8,9)]
for a,b,c in seq:
    print('a={0},b={1},c={2}'.format(a,b,c))
    


a=1,b=2,c=3
a=4,b=5,c=6
a=7,b=8,c=9


使用特殊语法*rest,用在函数签名中抓取任意长度的位置参数

In [11]:
values=1,2,3,4,5
a,b,*rest=values
a,b

(1, 2)

In [12]:
rest

[3, 4, 5]

与元组相比，列表的长度，内容可以被修改
list常用来在数据处理中实体化迭代器或生成器

In [13]:
gen=range(10)
gen


range(0, 10)

In [14]:
list(gen)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [15]:
tup=('foo','bar','baz')
b_list=list(tup)

In [16]:
b_list

['foo', 'bar', 'baz']

In [17]:
b_list.insert(1,'err')

In [18]:
b_list

['foo', 'err', 'bar', 'baz']

In [19]:
b_list.pop(2)

'bar'

In [20]:
b_list

['foo', 'err', 'baz']

通过加法将列表串联起来计算量较大，因为要新建立一个列表，并且要复制对象，用extend追加元素，尤其是到一个大列表中
更可取

In [21]:
everything=[]
for chunk in list_of_lists:
    everything.extend(chunk)

NameError: name 'list_of_lists' is not defined

bisect模块向已排序的列表中插入值。bisect.bisect可以找到插入值后仍保持排序的位置，bisect.insort是向这个位置插入值

In [7]:
import bisect
c=[1,2,2,2,3,4,7]
bisect.bisect(c,2)

4

In [8]:
bisect.bisect(c,5)

6

In [9]:
bisect.insort(c,5)
c

[1, 2, 2, 2, 3, 4, 5, 7]

enumerate(枚举)

In [26]:
i=0
for value in collection:
    i+=1
for i,value in enumerate(collection):
    

SyntaxError: unexpected EOF while parsing (<ipython-input-26-c251903b158d>, line 5)

In [28]:
some_list=['foo','sdv','asf']
mapping={}
for i,v in enumerate(some_list):
    mapping[i]=v
mapping

{0: 'foo', 1: 'sdv', 2: 'asf'}

zip可以将多个列表，元组或其他序列成对组合成一个元组列表

In [29]:
seq1=['er','dsg','dsg']
seq2=['sf','dsf','dsg']
zipped=zip(seq1,seq2)
list(zipped)


[('er', 'sf'), ('dsg', 'dsf'), ('dsg', 'dsg')]

In [30]:
seq3=[False,True]
list(zip(seq1,seq2,seq3))

[('er', 'sf', False), ('dsg', 'dsf', True)]

zip的常见用法之一是同时迭代多个序列，可能结合enumerate使用

In [35]:
for i,(a,b) in enumerate(zip(seq1,seq2)):
    print('{0}:{1},{2}'.format(i,a,b))

0:er,sf
1:dsg,dsf
2:dsg,dsg


reversed函数可以从后向前迭代一个序列     list加东西用（）

In [37]:
list(reversed(range(10)))

[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

字典

In [1]:
empty_dict={}
d1={'a':'some value','b':[1,2,3]}
d1

{'a': 'some value', 'b': [1, 2, 3]}

In [2]:
d1[7]='an integer'
d1

{'a': 'some value', 'b': [1, 2, 3], 7: 'an integer'}

In [4]:
d1.pop(7)

'an integer'

In [5]:
d1['shfkl']='dsnv'
d1

{'a': 'some value', 'b': [1, 2, 3], 'shfkl': 'dsnv'}

In [10]:
list(d1.keys())

['a', 'b', 'shfkl']

In [11]:
list(d1.values())

['some value', [1, 2, 3], 'dsnv']

用序列创建字典

mapping={}
for key,value in zip(key_list,value_list):
    mapping[key]=value
    

In [14]:
mapping=dict(zip(range(5),reversed(range(5))))
mapping

{0: 4, 1: 3, 2: 2, 3: 1, 4: 0}

字典的值属于其他集合，如列表。例如，可以通过首字母，将一个列表中的单词分类

In [19]:
words=['apple','bat','bar','atom']
by_letter={}
for word in words:
    letter=word[0]
    if letter not in by_letter:
        by_letter[letter]=[word]
    else:
        by_letter[letter].append(word)
by_letter

{'a': ['apple', 'atom'], 'b': ['bat', 'bar']}

setdefault方法就是干这个的，前面的for循环可以改写成


In [20]:
for word in words:
    letter=word[0]
    by_letter.setdefault(letter,[]).append(word)

collection 模块有一个很有用的类，defaultdict,它可以进一步简化上面。

In [22]:
from collections import defaultdict
by_letter=defaultdict(list)
for word in words:
    by_letter[word[0]].append(word)

有效的键类型
字典的值可以是任何的python对象，而键通常是不可变的（整数，浮点型，字符串）或元组（元组中对象是不可变的）。被称为‘可哈希性’。
可以用hash函数检测一个对象是否是可哈希的（可被用作字典的键）

In [24]:
hash('string')

7327077090623991189

In [26]:
hash((1,2,(3,4)))

-2725224101759650258

In [27]:
hash((1,2,[3,4]))

TypeError: unhashable type: 'list'

要把列表当成键，一种方法是将列表转化成元组，只要内部元素可以被哈希，它就可以被哈希

In [28]:
d={}
d[tuple([1,2,3])]=5
d

{(1, 2, 3): 5}

与字典类似，集合元素一般都是不可变的，要获得类似列表的元素，要先转化成元组

In [29]:
my_data=[1,2,3,4]
my_set={tuple(my_data)}
my_set

{(1, 2, 3, 4)}

In [30]:
a_set={1,2,3,4,5}
{1,2,3}.issubset(a_set)


True

In [33]:
a_set.issuperset({1,2,3})

True

expr for val in collection if condition
等同于下面的for循环

result=[]
for val in collecction:
    if condition:
        result.append(expr)

In [39]:
strings=['a','dsf','degj','ytdg','fj']
[x.upper() for x in strings if len(x)>2]

['DSF', 'DEGJ', 'YTDG']

集合的推倒与列表很像，只不过用的尖括号

In [40]:
unique_lengths={len(x) for x in strings}
unique_lengths

{1, 2, 3, 4}

作为字典推倒式的例子，可以创建一个字符串的查找映射表以确定它在列表中的位置

In [41]:
loc_mapping={val:index for index,val in enumerate(strings)}
loc_mapping

{'a': 0, 'dsf': 1, 'degj': 2, 'ytdg': 3, 'fj': 4}

In [43]:
all_data=[['rehn','tdjmd','ewyh','renojtie','fdnmoe'],
         ['fdkn','rtihm','gnmpd','egnpm']]
name_of_interest=[]
for names in all_data:
    enough_es=[name for name in names if name.count('e')>=2]
    name_of_interest.extend(enough_es)

In [44]:
name_of_interest

['renojtie']

In [45]:
some_tuples=[(1,2,3),(4,5,6),(7,8,9)]
flattened=[x for tup in some_tuples for x in tup]
flattened

[1, 2, 3, 4, 5, 6, 7, 8, 9]

for表达式的顺序与嵌套for循环的顺序一样


In [46]:
flattened=[]
for tup in some_tuples:
    for x in tup:
        flattened.append(x)

命名空间，作用域，局部函数

任何在函数中赋值的变量都默认是被分配到局部命名空间，局部命名空间是在函数被调用时创建的，参数会立即填入被调用空间，在函数执行完毕后，局部命名空间就会被销毁

In [47]:
def fun():
    a=[]
    for i in range(5):
        a.append(i)

调用fun()后，首先会创建出空列表a,然后添加5个元素，最后a会在函数推出后被销毁

返回多个值

In [49]:
def f():
    a=3
    b=4
    c=6
    return a,b,c
a,b,c=f()

In [50]:
f()

(3, 4, 6)

In [51]:
def f():
    a=3
    b=4
    c=6
    return {'a':a,'b':b,'c':c}
return_value=f()

In [52]:
return_value

{'a': 3, 'b': 4, 'c': 6}

In [54]:
states=['dj?fh','dsvbo','fdlkjp!','idsoi psaio',' know g#jk']
import re
def clean_strings(strings):
    result=[]
    for value in strings:
        value=value.strip()
        value=re.sub('[!#?]','',value)
        value=value.title()
        result.append(value)
    return result
clean_strings(states)

['Djfh', 'Dsvbo', 'Fdlkjp', 'Idsoi Psaio', 'Know Gjk']

In [55]:
def remove_punctuation(value):
    return re.sub('[!#?]','',value)
clean_ops=[str.strip,remove_punctuation,str.title]
def clean_strings(strings,ops):
    result=[]
    for value in strings:
        for function in ops:
            value=function(value)
        result.append(value)
    return result
    
    

In [56]:
clean_strings(states,clean_ops)

['Djfh', 'Dsvbo', 'Fdlkjp', 'Idsoi Psaio', 'Know Gjk']

In [57]:
for x in map(remove_punctuation,states):
    print(x)

djfh
dsvbo
fdlkjp
idsoi psaio
 know gjk


匿名函数（lambda）

In [58]:
def short_function(x):
    return x*2
equiv_anon=lambda x:x*2

很多数据转换函数都是以函数作为参数的，直接传入lambda比编写完整函数声明要省略好多字，比将lambda赋值给一个变量还要少输入很多字

In [59]:
def apply_to_list(some_list,f):
    return [f(x) for x in some_list]
ints=[4,0,1,5,9]
apply_to_list(ints,lambda x:x*2)

[8, 0, 2, 10, 18]

In [60]:
strings=['foo','card','abab','bar','card']
strings.sort(key=lambda x:len(set(list(x))))
strings

['foo', 'abab', 'bar', 'card', 'card']

柯里化：部分参数应用

In [61]:
def add_numbers(x,y):
    return x+y
add_five=lambda y:add_numbers(5,y)

 add_numbers第二个参数称为柯里化，就是定义了一个调用现有函数的新函数而已
 内置的functools模块可以用partial函数简化

In [62]:
from functools import partial
add_five=partial(add_numbers,5)

生成器（gemerator）是构造新的可迭代对象的一种简单方式。一般的函数执行之后只会返回单个值，而生成器则没返回一个值后暂停，指导下个值被请求再继续

In [63]:
def squares(n=10):
    print('Generating squares from 1 to {0}'.format(n**2))
    for i in range(1,n+1):
        yield i**2

调用生成器没有代码会被立即执行


In [64]:
gen=squares()
gen

<generator object squares at 0x000001BA4CF80A40>

直到你从该生成器中请求元素时，它才会开始执行

In [65]:
for x in gen:
    print(x,end=' ')

Generating squares from 1 to 100
1 4 9 16 25 36 49 64 81 100 

生成器表达式是一种更简单构造生成器的方式

In [66]:
gen=(x**2 for x in range(100))
gen

<generator object <genexpr> at 0x000001BA4CF806D0>

等价于下面

In [67]:
def make_gun():
    for x in range(100):
        yield x**2
gen=make_gun()

错误和异常处理

In [68]:
float('1.4652')

1.4652

In [69]:
def attemt_float(x):
    try:
        return float(x)
    except:
        return x

In [70]:
attemt_float(1.8641)

1.8641

In [71]:
attemt_float('dsds,g')

'dsds,g'

f=open(path,'w')
try:
    write_to_file(f)
except:
    print('failed')
else:
    print('success')

finally:
    f.close()

In [1]:
import numpy as np
my_arr=np.arange(100000)
my_list=list(range(100000))

In [3]:
%time for _ in range(10):my_arr2=my_arr*2

Wall time: 1.99 ms


In [6]:
%time for _ in range(10):my_list2=[x*2 for x in my_list]

Wall time: 53.9 ms


第四章
ndarray是一个通用同构数据多维容器，其中所有元素必须是同类型的。每个数组都有一个shape（表示各维度大小的元组），和一个dtype（用于说明数组数据类型的对象）

创建ndarray   最简单的方法就是使用array函数，它接受一切序列行对象（包括其他数组）

In [7]:
data1=[2,5,7,8.6]
arr1=np.array(data1)
arr1

array([2. , 5. , 7. , 8.6])

嵌套序列（由一组等长列表组成的列表）将会被转换为一组多维数组

In [9]:
data2=[[1,2,3,4],[7.5,8.3,6,4]]
arr2=np.array(data2)
arr2

array([[1. , 2. , 3. , 4. ],
       [7.5, 8.3, 6. , 4. ]])

In [10]:
arr2.ndim

2

In [11]:
arr2.shape

(2, 4)

In [12]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

可以通过ndarray的astype方法明确的将一个数组从一个dtype转化成另一个

In [13]:
arr=np.array([1,7,6,3])
arr.dtype

dtype('int32')

整数被换成了浮点数

In [15]:
flaot_arr=arr.astype(np.float64)
flaot_arr.dtype

dtype('float64')

某字符串表示的全时数字，可以用astype将其转换成数值类型

In [17]:
strings=np.array(['1.25','2.88','452'],dtype=np.string_)
strings.astype(np.float64)

array([  1.25,   2.88, 452.  ])

跟列表最重要的区别是，数组的切片是原始数据的视图。这意味着数据不会被复制，视图上的任何修改都会直接反映到源数组上

如果你想得到的是ndarray切片的一份副本而非视图，就要用arr[5：8].copy操作

In [ ]:
布尔型索引

In [18]:
names=np.array(['bob','joe','will','bob','will','joe','joe'])
data=np.random.randn(7,4)
names

array(['bob', 'joe', 'will', 'bob', 'will', 'joe', 'joe'], dtype='<U4')

In [19]:
data

array([[ 0.36848759,  0.70574278, -0.03115891,  0.97991711],
       [ 1.33602759, -0.23584407, -0.35017664,  0.57298425],
       [-0.96839472, -0.68047909,  0.17094201, -1.95115702],
       [-0.13649759, -1.50578995, -0.48101079, -1.89919534],
       [-1.44268027, -1.75674848,  0.52627402, -0.29039748],
       [ 0.87631036, -0.66531163, -0.7894812 ,  0.08141269],
       [-0.75183771, -1.19174762,  0.97756831,  0.22961842]])

In [20]:
names=='bob'

array([ True, False, False,  True, False, False, False])

In [21]:
data[names=='bob']

array([[ 0.36848759,  0.70574278, -0.03115891,  0.97991711],
       [-0.13649759, -1.50578995, -0.48101079, -1.89919534]])

In [22]:
data[names=='bob',2:]

array([[-0.03115891,  0.97991711],
       [-0.48101079, -1.89919534]])

In [23]:
names!='bob'


array([False,  True,  True, False,  True,  True,  True])

In [24]:
data[~(names=='bob')]

array([[ 1.33602759, -0.23584407, -0.35017664,  0.57298425],
       [-0.96839472, -0.68047909,  0.17094201, -1.95115702],
       [-1.44268027, -1.75674848,  0.52627402, -0.29039748],
       [ 0.87631036, -0.66531163, -0.7894812 ,  0.08141269],
       [-0.75183771, -1.19174762,  0.97756831,  0.22961842]])

In [ ]:
选取这三个名字中的两个需要组合应用多个条件，&（和）·|（或）

In [25]:
mask=(names=='bob')|(names=='will')
mask

array([ True, False,  True,  True,  True, False, False])

In [26]:
data[mask]

array([[ 0.36848759,  0.70574278, -0.03115891,  0.97991711],
       [-0.96839472, -0.68047909,  0.17094201, -1.95115702],
       [-0.13649759, -1.50578995, -0.48101079, -1.89919534],
       [-1.44268027, -1.75674848,  0.52627402, -0.29039748]])

In [27]:
data[data<0]=0
data

array([[0.36848759, 0.70574278, 0.        , 0.97991711],
       [1.33602759, 0.        , 0.        , 0.57298425],
       [0.        , 0.        , 0.17094201, 0.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.52627402, 0.        ],
       [0.87631036, 0.        , 0.        , 0.08141269],
       [0.        , 0.        , 0.97756831, 0.22961842]])

In [28]:
data[names!='bob']=6
data

array([[0.36848759, 0.70574278, 0.        , 0.97991711],
       [6.        , 6.        , 6.        , 6.        ],
       [6.        , 6.        , 6.        , 6.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [6.        , 6.        , 6.        , 6.        ],
       [6.        , 6.        , 6.        , 6.        ],
       [6.        , 6.        , 6.        , 6.        ]])

In [ ]:
花式索引

In [29]:
arr=np.empty((8,4))
for i in range(8):
    arr[i]=i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [30]:
arr[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [ ]:
一次传入多个索引会有些特别，返回的是一个一维数组，其中的元素对应各个索引元组

In [31]:
arr=np.arange(32).reshape((8,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [32]:
arr[[1,5,7,2],[0,3,1,2]]

array([ 4, 23, 29, 10])

In [33]:
arr[[1,5,7,2]][:,[0,3,1,2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [34]:
arr=np.arange(16).reshape((2,2,4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [35]:
arr.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [36]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [37]:
arr.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [39]:
arr=np.random.randn(7)*5
arr

array([-5.31382485, -6.13436837,  1.91552769, -2.99371206, -8.32073861,
       -3.75470747,  1.03690905])

In [40]:
remainder,whole_part=np.modf(arr)
remainder

array([-0.31382485, -0.13436837,  0.91552769, -0.99371206, -0.32073861,
       -0.75470747,  0.03690905])

In [41]:
whole_part

array([-5., -6.,  1., -2., -8., -3.,  1.])

将条件逻辑表示为数组运算

numpy.where是三元表达式x if condition else y的矢量化版本

In [43]:
xarr=np.array([1.1,1.2,1.3,1.4,1.5])
yarr=np.array([2.1,2.2,2.3,2.4,2.5])
cond=np.array([True,False,True,True,False])
result=[(x if c else y)
       for x,y,c in zip(xarr,yarr,cond)]
result

[1.1, 2.2, 1.3, 1.4, 2.5]

若使用np.where非常简洁

In [44]:
result=np.where(cond,xarr,yarr)
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

np.where的第二个，第三个参数不必是数组，它们都可以是标量值，假设在一个随机矩阵中，把争执替换成2，负值替换成-2

In [46]:
arr=np.random.randn(4,4)
arr

array([[ 0.2033117 ,  0.73279217,  0.04449127, -0.47149265],
       [-0.74133593,  1.06657805, -0.05481635, -0.91631768],
       [-0.4868707 , -2.14969768, -1.03276707, -1.24474282],
       [-0.35126817,  1.38894274, -1.26488418,  0.58772828]])

In [47]:
arr>0

array([[ True,  True,  True, False],
       [False,  True, False, False],
       [False, False, False, False],
       [False,  True, False,  True]])

In [48]:
np.where(arr>0,2,-2)

array([[ 2,  2,  2, -2],
       [-2,  2, -2, -2],
       [-2, -2, -2, -2],
       [-2,  2, -2,  2]])

In [49]:
np.where(arr>0,2,arr)

array([[ 2.        ,  2.        ,  2.        , -0.47149265],
       [-0.74133593,  2.        , -0.05481635, -0.91631768],
       [-0.4868707 , -2.14969768, -1.03276707, -1.24474282],
       [-0.35126817,  2.        , -1.26488418,  2.        ]])

如cumsum和cumprod之类的则不聚合，产生一个由中间结果组成的数组

In [50]:
arr=np.array([0,1,3,4,5,6])
arr.cumsum()

array([ 0,  1,  4,  8, 13, 19], dtype=int32)

In [ ]:
cumsum累加，cumprod累乘

In [51]:
arr=np.array([[0,1,2],[3,4,5],[6,7,8]])
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [52]:
arr.cumsum(axis=0)

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]], dtype=int32)

In [53]:
arr.cumprod(axis=1)

array([[  0,   0,   0],
       [  3,  12,  60],
       [  6,  42, 336]], dtype=int32)

In [55]:
arr=np.random.randn(100)
(arr>0).sum()

45

唯一化

In [57]:
names=np.array(['bob','hdsj','dskjhk','bob','hdsj'])
np.unique(names)

array(['bob', 'dskjhk', 'hdsj'], dtype='<U6')

跟等价的纯python代码比较一下

In [58]:
sorted(set(names))

['bob', 'dskjhk', 'hdsj']

In [59]:
arr=np.arange(10)
np.save('some_array',arr)

In [60]:
np.load('some_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
np.savez('array_archive.npz',a=arr,b=arr)
arch=np.load('array_archive.npz')
arch['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
arch['b']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
x=np.array([[1,2,3],[4,5,6]])
np.dot(x,np.ones(3))

array([ 6., 15.])